name: Telegram Notifications

on:
  fork:
    types: [created]
  pull_request:
    types: [opened, closed]
  push:
    branches:
      - '*'

jobs:
  notify-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GITHUB_EVENT: ${{ github.event_name }}
          PR_ACTION: ${{ github.event.action }}
        run: |
          if [ "$GITHUB_EVENT" = "fork" ]; then
            MESSAGE="🚀 New fork created by ${{ github.actor }}!"
          elif [ "$GITHUB_EVENT" = "pull_request" ] && [ "$PR_ACTION" = "opened" ]; then
            MESSAGE="🔄 New pull request by ${{ github.actor }}: ${{ github.event.pull_request.html_url }}"
          elif [ "$GITHUB_EVENT" = "pull_request" ] && [ "$PR_ACTION" = "closed" ]; then
            if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
              MESSAGE="✅ Pull request merged by ${{ github.actor }}: ${{ github.event.pull_request.html_url }}"
            else
              MESSAGE="❌ Pull request closed by ${{ github.actor }}: ${{ github.event.pull_request.html_url }}"
            fi
          elif [ "$GITHUB_EVENT" = "push" ]; then
            MESSAGE="🚀 New code pushed to main by ${{ github.actor }}."
          else
            MESSAGE="ℹ️ Event not recognized for notification."
          fi

          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
          -d "chat_id=$TELEGRAM_CHAT_ID" \
          -d "text=$MESSAGE"
