name: Telegram Notifications

on:
  fork:
    types: [created]
  pull_request:
    types: [opened, closed]
  push:
    branches:
      - '*'

jobs:
  notify-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        env:
          TELEGRAM_BOT_TOKEN: '8071164350:AAE6kavzLpQ5sO9DN1IGkjutnIMADhQBPc0'
          TELEGRAM_CHAT_ID: '582130596'
          GITHUB_EVENT: ${{ github.event_name }}
          PR_ACTION: ${{ github.event.action }}
        run: |
          if [ "$GITHUB_EVENT" = "fork" ]; then
            MESSAGE="🚀 New fork created by ${{ github.actor }}!"
          elif [ "$GITHUB_EVENT" = "pull_request" ] && [ "$PR_ACTION" = "opened" ]; then
            MESSAGE="🔄 New pull request by ${{ github.actor }}: ${{ github.event.pull_request.html_url }}"
          elif [ "$GITHUB_EVENT" = "pull_request" ] && [ "$PR_ACTION" = "closed" ]; then
            if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
              MESSAGE="✅ Pull request merged by ${{ github.actor }}: ${{ github.event.pull_request.html_url }}"
            else
              MESSAGE="❌ Pull request closed by ${{ github.actor }}: ${{ github.event.pull_request.html_url }}"
            fi
          elif [ "$GITHUB_EVENT" = "push" ]; then
            MESSAGE="🚀 New code pushed to branch ${{ github.ref_name }} by ${{ github.actor }}."
          elif [ "$GITHUB_EVENT" = "repository_dispatch" ] && [ "$DEPLOYMENT_STATE" = "SUCCEEDED" ]; then
            MESSAGE="🎉 Vercel deployment succeeded for the latest update!"
          elif [ "$GITHUB_EVENT" = "repository_dispatch" ] && [ "$DEPLOYMENT_STATE" = "FAILED" ]; then
            MESSAGE="⚠️ Vercel deployment failed. Please check the deployment logs."
          else
            MESSAGE="ℹ️ Event not recognized for notification."
          fi

          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
               -H "Content-Type: application/json" \
               -d "{\"chat_id\": \"$TELEGRAM_CHAT_ID\", \"text\": \"$MESSAGE\"}"
